#!/usr/bin/env node
/**
 * Sync built artifacts into the guard worker:
 * 1. examples/minimal-site/dist -> packages/guard-worker/assets/site/
 * 2. packages/login-ui/dist/index.html  -> src/pages/login-spa.ts
 * 3. packages/admin-ui/dist/index.html  -> src/pages/admin-spa.ts
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const worker = join(root, 'packages/guard-worker');
const siteOut = join(worker, 'assets/site');

const pageJobs = [
  {
    dist: join(root, 'packages/login-ui/dist/index.html'),
    out: join(worker, 'src/pages/login-spa.ts'),
    exportName: 'LOGIN_SPA_HTML',
    label: 'login SPA',
  },
  {
    dist: join(root, 'packages/admin-ui/dist/index.html'),
    out: join(worker, 'src/pages/admin-spa.ts'),
    exportName: 'ADMIN_SPA_HTML',
    label: 'admin SPA',
  },
];

mkdirSync(siteOut, { recursive: true });
try {
  for (const entry of readdirSync(siteOut, { withFileTypes: true })) {
    try {
      rmSync(join(siteOut, entry.name), { recursive: true, force: true });
    } catch {
      // ignore busy on Windows
    }
  }
} catch {
  // ignore
}

const exampleDist = join(root, 'examples/minimal-site/dist');
if (existsSync(exampleDist)) {
  cpSync(exampleDist, siteOut, { recursive: true });
  console.log('[sync-assets] site from examples/minimal-site/dist');
} else {
  writeFileSync(
    join(siteOut, 'placeholder.html'),
    '<!doctype html><meta charset="utf-8"><title>empty site</title><p>Run npm run build:example</p>',
  );
  console.log('[sync-assets] site placeholder (no example dist)');
}

for (const job of pageJobs) {
  if (existsSync(job.dist)) {
    const html = readFileSync(job.dist, 'utf8');
    const ts = [
      '/** AUTO-GENERATED by scripts/sync-assets.mjs - do not edit. */',
      `export const ${job.exportName} = ${JSON.stringify(html)};`,
      '',
    ].join('\n');
    writeFileSync(job.out, ts);
    console.log(`[sync-assets] ${job.label} embedded, bytes=${html.length}`);
  } else {
    const ts = [
      `/** Placeholder replaced by scripts/sync-assets.mjs after building. */`,
      `export const ${job.exportName} = '';`,
      '',
    ].join('\n');
    writeFileSync(job.out, ts);
    console.log(`[sync-assets] ${job.label} not built`);
  }
}

console.log('[sync-assets] done');
